export const PALAVRAS = [
  { palavra: 'JAVASCRIPT', dica: 'Linguagem de programação web' },
  { palavra: 'PYTHON', dica: 'Linguagem famosa por sua simplicidade' },
  { palavra: 'PROGRAMACAO', dica: 'O que desenvolvedores fazem' },
  { palavra: 'ALGORITMO', dica: 'Sequência de passos para resolver um problema' },
  { palavra: 'COMPILADOR', dica: 'Transforma código em executável' },
  { palavra: 'FRAMEWORK', dica: 'Estrutura para desenvolvimento' },
  { palavra: 'INTERFACE', dica: 'O que o usuário vê e interage' },
  { palavra: 'RECURSAO', dica: 'Função que chama a si mesma' },
  { palavra: 'VARIAVEL', dica: 'Armazena um valor na memória' },
  { palavra: 'TYPESCRIPT', dica: 'JavaScript com tipagem estática' },
  { palavra: 'COMPONENTE', dica: 'Bloco reutilizável no React' },
  { palavra: 'REPOSITORIO', dica: 'Onde o código fica guardado no Git' },
  { palavra: 'DEPLOY', dica: 'Colocar a aplicação no ar' },
  { palavra: 'DEBUGGING', dica: 'Processo de encontrar e corrigir erros' },
  { palavra: 'HTML', dica: 'Estrutura de páginas web' },
  { palavra: 'CSS', dica: 'Estiliza páginas web' },
  { palavra: 'API', dica: 'Comunicação entre sistemas' },
  { palavra: 'FUNCAO', dica: 'Bloco de código reutilizável' },
  { palavra: 'ARRAY', dica: 'Lista de elementos' },
  { palavra: 'OBJETO', dica: 'Estrutura com chave e valor' },
  { palavra: 'CLASSE', dica: 'Modelo para criar objetos' },
  { palavra: 'RESPONSIVO', dica: 'Adapta a diferentes telas' },
  { palavra: 'VERSIONAMENTO', dica: 'Controle de mudanças no código' },
]